/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anime;

import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;

/**
 *
 * @author mtech
 */
public class mainview extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    static Long id;
    Long id1;
    Long id2;
    Long id3;
    Long id4;

    public mainview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pop_text2 = new javax.swing.JLabel();
        pop_text1 = new javax.swing.JLabel();
        pop_text3 = new javax.swing.JLabel();
        pop_text4 = new javax.swing.JLabel();
        pop_text5 = new javax.swing.JLabel();
        pop_text6 = new javax.swing.JLabel();
        pop_text7 = new javax.swing.JLabel();
        pop_text8 = new javax.swing.JLabel();
        pop_text9 = new javax.swing.JLabel();
        pop_text10 = new javax.swing.JLabel();
        pop_text11 = new javax.swing.JLabel();
        pop_text12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchinp = new javax.swing.JTextField();
        view4 = new javax.swing.JPanel();
        pop4 = new javax.swing.JLabel();
        view2 = new javax.swing.JPanel();
        pop2 = new javax.swing.JLabel();
        view3 = new javax.swing.JPanel();
        pop3 = new javax.swing.JLabel();
        view1 = new javax.swing.JPanel();
        pop1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 960));
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 960));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("episodes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 870, 130, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 770, 130, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("averageScore");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 820, 130, 40);

        jPanel5.setBackground(new java.awt.Color(255, 40, 23));
        jPanel5.setOpaque(false);

        pop_text2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text2.setForeground(new java.awt.Color(255, 255, 255));

        pop_text1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text1.setForeground(new java.awt.Color(255, 255, 255));

        pop_text3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text3.setForeground(new java.awt.Color(255, 255, 255));

        pop_text4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text4.setForeground(new java.awt.Color(255, 255, 255));

        pop_text5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text5.setForeground(new java.awt.Color(255, 255, 255));

        pop_text6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text6.setForeground(new java.awt.Color(255, 255, 255));

        pop_text7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text7.setForeground(new java.awt.Color(255, 255, 255));

        pop_text8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text8.setForeground(new java.awt.Color(255, 255, 255));

        pop_text9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text9.setForeground(new java.awt.Color(255, 255, 255));

        pop_text10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text10.setForeground(new java.awt.Color(255, 255, 255));

        pop_text11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text11.setForeground(new java.awt.Color(255, 255, 255));

        pop_text12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pop_text12.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(pop_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(pop_text2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(pop_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pop_text4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(pop_text5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(pop_text6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(pop_text7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pop_text8, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(pop_text9, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(pop_text10, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(pop_text11, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(pop_text12, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pop_text2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop_text4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pop_text6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop_text7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop_text5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop_text8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pop_text10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop_text11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop_text9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop_text12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(210, 770, 1120, 160);

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1080, 30, 120, 70);

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Popular Anime");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(650, 370, 310, 70);

        searchinp.setBackground(new java.awt.Color(0, 0, 0));
        searchinp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        searchinp.setForeground(new java.awt.Color(255, 255, 255));
        searchinp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 2, true));
        searchinp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchinpKeyPressed(evt);
            }
        });
        getContentPane().add(searchinp);
        searchinp.setBounds(1200, 40, 260, 40);

        view4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view4.setOpaque(false);
        view4.setLayout(null);

        pop4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pop4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pop4MouseClicked(evt);
            }
        });
        view4.add(pop4);
        pop4.setBounds(0, 2, 240, 320);

        getContentPane().add(view4);
        view4.setBounds(1090, 450, 240, 320);

        view2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view2.setOpaque(false);
        view2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pop2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pop2MouseClicked(evt);
            }
        });
        view2.add(pop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 320));

        getContentPane().add(view2);
        view2.setBounds(520, 450, 240, 320);

        view3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view3.setOpaque(false);
        view3.setLayout(null);

        pop3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pop3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pop3MouseClicked(evt);
            }
        });
        view3.add(pop3);
        pop3.setBounds(0, 2, 240, 320);

        getContentPane().add(view3);
        view3.setBounds(800, 450, 240, 320);

        view1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view1.setOpaque(false);
        view1.setLayout(null);

        pop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pop1MouseClicked(evt);
            }
        });
        view1.add(pop1);
        pop1.setBounds(0, 2, 240, 320);

        getContentPane().add(view1);
        view1.setBounds(220, 450, 240, 320);

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ANIME ME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 200, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anime/165657.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static Long getid() {
        return id;
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Connection c = new Connection();
        c.get_pop();
        this.pop1.setIcon(new ImageIcon(c.pop1));
        this.pop2.setIcon(new ImageIcon(c.pop2));
        this.pop3.setIcon(new ImageIcon(c.pop3));
        this.pop4.setIcon(new ImageIcon(c.pop4));
        this.pop_text1.setText(String.valueOf(c.th1.get("romaji")));
        this.pop_text2.setText(String.valueOf(c.th2.get("romaji")));
        this.pop_text3.setText(String.valueOf(c.th3.get("romaji")));
        this.pop_text4.setText(String.valueOf(c.th4.get("romaji")));
        this.pop_text5.setText(String.valueOf(c.p1));
        this.pop_text6.setText(String.valueOf(c.p2));
        this.pop_text7.setText(String.valueOf(c.p3));
        this.pop_text8.setText(String.valueOf(c.p4));
        this.pop_text9.setText(String.valueOf(c.e1));
        this.pop_text10.setText(String.valueOf(c.e2));
        this.pop_text11.setText(String.valueOf(c.e3));
        this.pop_text12.setText(String.valueOf(c.e4));
        this.id1 = (Long) c.first.get("id");
        this.id2 = (Long) c.Second.get("id");
        this.id3 = (Long) c.third.get("id");
        this.id4 = (Long) c.forth.get("id");

    }//GEN-LAST:event_formWindowOpened

    void showingui() {

        Connection c = new Connection();
        c.getanime(searchinp.getText());
        if (c.first != null) {
            this.pop1.setIcon(new ImageIcon(c.pop1));
            this.pop_text1.setText(String.valueOf(c.th1.get("romaji")));
            this.pop_text5.setText(String.valueOf(c.p1));
            this.pop_text12.setText(String.valueOf(c.e4));
            this.id1 = (Long) c.first.get("id");
        }
        if (c.Second != null) {
            this.pop2.setIcon(new ImageIcon(c.pop2));
            this.pop_text2.setText(String.valueOf(c.th2.get("romaji")));
            this.pop_text6.setText(String.valueOf(c.p2));
            this.pop_text10.setText(String.valueOf(c.e2));
            this.id2 = (Long) c.Second.get("id");
        }
        if (c.third != null) {

            this.pop3.setIcon(new ImageIcon(c.pop3));

            this.pop_text3.setText(String.valueOf(c.th3.get("romaji")));

            this.pop_text7.setText(String.valueOf(c.p3));

            this.pop_text11.setText(String.valueOf(c.e3));
            this.id3 = (Long) c.third.get("id");

        }
        if (c.forth != null) {
            this.pop4.setIcon(new ImageIcon(c.pop4));
            this.pop_text4.setText(String.valueOf(c.th4.get("romaji")));
            this.pop_text8.setText(String.valueOf(c.p4));
            this.pop_text12.setText(String.valueOf(c.e4));
            this.id4 = (Long) c.forth.get("id");
        }
        if (c.first == null) {
            JOptionPane.showMessageDialog(this, "We cant find the anime you are searching about D:");
        }
    }
    private void searchinpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchinpKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            showingui();

        }

    }//GEN-LAST:event_searchinpKeyPressed
    public anime_view av = new anime_view();


    private void pop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pop1MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 1) {

            this.setVisible(false);
            av.setLocationRelativeTo(null);
            av.setVisible(true);
            id = id1;

        }
    }//GEN-LAST:event_pop1MouseClicked

    private void pop2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pop2MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {

            this.dispose();
            av.setLocationRelativeTo(null);
            av.setVisible(true);
            id = id2;
        }
    }//GEN-LAST:event_pop2MouseClicked

    private void pop3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pop3MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {

            this.dispose();
            av.setLocationRelativeTo(null);
            av.setVisible(true);
            id = id3;
        }
    }//GEN-LAST:event_pop3MouseClicked

    private void pop4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pop4MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {

            this.dispose();
            av.setLocationRelativeTo(null);
            av.setVisible(true);
            id = id4;
        }
    }//GEN-LAST:event_pop4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel pop1;
    private javax.swing.JLabel pop2;
    private javax.swing.JLabel pop3;
    private javax.swing.JLabel pop4;
    private javax.swing.JLabel pop_text1;
    private javax.swing.JLabel pop_text10;
    private javax.swing.JLabel pop_text11;
    private javax.swing.JLabel pop_text12;
    private javax.swing.JLabel pop_text2;
    private javax.swing.JLabel pop_text3;
    private javax.swing.JLabel pop_text4;
    private javax.swing.JLabel pop_text5;
    private javax.swing.JLabel pop_text6;
    private javax.swing.JLabel pop_text7;
    private javax.swing.JLabel pop_text8;
    private javax.swing.JLabel pop_text9;
    private javax.swing.JTextField searchinp;
    private javax.swing.JPanel view1;
    private javax.swing.JPanel view2;
    private javax.swing.JPanel view3;
    private javax.swing.JPanel view4;
    // End of variables declaration//GEN-END:variables
}
